Gem::Specification.new do |s|
  s.name        = 'fism_fpgrowth'
  s.version     = '0.1.0'
  s.date        = '2015-07-30'
  s.summary     = "Ruby wrapper for Christian Borgelt's FPGrowth implementation"
  s.description = "Ruby wrapper for Christian Borgelt's FPGrowth implementation for frequent itemset mining."
  s.authors     = ['Eugen Kuksa']
  s.email       = 'eugenk@informatik.uni-bremen.de'
  s.files       = ['lib/fism_fpgrowth.rb',
                   'Makefile',
                   'vendor/apriori/src',
                   'vendor/apriori/src/apriori.mak',
                   'vendor/apriori/src/istree.c',
                   'vendor/apriori/src/istree.h',
                   'vendor/apriori/src/makefile',
                   'vendor/fpgrowth/doc',
                   'vendor/fpgrowth/doc/fpgrowth.html',
                   'vendor/fpgrowth/doc/line.gif',
                   'vendor/fpgrowth/doc/mit-license.txt',
                   'vendor/fpgrowth/doc/up.gif',
                   'vendor/fpgrowth/ex/flg2set',
                   'vendor/fpgrowth/ex/hdr2set',
                   'vendor/fpgrowth/ex/row2set',
                   'vendor/fpgrowth/ex/tab2set',
                   'vendor/fpgrowth/ex/test1.csv',
                   'vendor/fpgrowth/ex/test1.tab',
                   'vendor/fpgrowth/ex/test2.tab',
                   'vendor/fpgrowth/ex/test3.tab',
                   'vendor/fpgrowth/ex/test4.tab',
                   'vendor/fpgrowth/ex/test5.tab',
                   'vendor/fpgrowth/ex/test6.tab',
                   'vendor/fpgrowth/ex/tid2set',
                   'vendor/fpgrowth/src/fpgrowth.c',
                   'vendor/fpgrowth/src/fpgrowth.h',
                   'vendor/fpgrowth/src/fpgrowth.mak',
                   'vendor/fpgrowth/src/makefile',
                   'vendor/math/doc/mit-license.txt',
                   'vendor/math/src/chi2.c',
                   'vendor/math/src/chi2.h',
                   'vendor/math/src/gamma.c',
                   'vendor/math/src/gamma.h',
                   'vendor/math/src/makefile',
                   'vendor/math/src/math.mak',
                   'vendor/math/src/ruleval.c',
                   'vendor/math/src/ruleval.h',
                   'vendor/tract/doc/mit-license.txt',
                   'vendor/tract/src/clomax.c',
                   'vendor/tract/src/clomax.h',
                   'vendor/tract/src/fim16.c',
                   'vendor/tract/src/fim16.h',
                   'vendor/tract/src/makefile',
                   'vendor/tract/src/patspec.c',
                   'vendor/tract/src/patspec.h',
                   'vendor/tract/src/report.c',
                   'vendor/tract/src/report.h',
                   'vendor/tract/src/tract.c',
                   'vendor/tract/src/tract.h',
                   'vendor/tract/src/tract.mak',
                   'vendor/util/doc/mit-license.txt',
                   'vendor/util/src/arrays.c',
                   'vendor/util/src/arrays.h',
                   'vendor/util/src/error.h',
                   'vendor/util/src/escape.c',
                   'vendor/util/src/escape.h',
                   'vendor/util/src/fntypes.h',
                   'vendor/util/src/makefile',
                   'vendor/util/src/memsys.c',
                   'vendor/util/src/memsys.h',
                   'vendor/util/src/scanner.c',
                   'vendor/util/src/scanner.h',
                   'vendor/util/src/symtab.c',
                   'vendor/util/src/symtab.h',
                   'vendor/util/src/tabread.c',
                   'vendor/util/src/tabread.h',
                   'vendor/util/src/tabwrite.c',
                   'vendor/util/src/tabwrite.h',
                   'vendor/util/src/util.mak']
  s.extensions  = ['extconf.rb']
  s.homepage    = 'https://github.com/eugenk/fism_fpgrowth'
  s.license     = 'MIT'
  s.add_development_dependency 'rspec'
end
